{
  "swagger": "2.0",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/accounts/profile": {
      "get": {
        "summary": "Member Profile",
        "tags": [
          "Accounts"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "operationId": "profile",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Successfully return profile"
          }
        }
      }
    },
    "/queues/{job_queue_id}/jobs": {
      "get": {
        "summary": "List Jobs",
        "tags": [
          "Jobs"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "operationId": "jobs#index",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "job_queue_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully list jobs"
          },
          "401": {
            "description": "unauthorized"
          }
        }
      },
      "post": {
        "summary": "Create Job",
        "tags": [
          "Jobs"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "operationId": "jobs#create",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "job_queue_id",
            "in": "path",
            "required": true
          },
          {
            "name": "job",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/job"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully create job"
          },
          "422": {
            "description": "unprocessable entity"
          },
          "401": {
            "description": "unauthorized"
          }
        }
      }
    },
    "/queues": {
      "get": {
        "summary": "List Queues",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "operationId": "queues#index",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Successfully list queues"
          },
          "401": {
            "description": "unauthorized"
          }
        }
      },
      "post": {
        "summary": "Create Queue",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": [

            ]
          }
        ],
        "operationId": "queues#create",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "queue",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/queue"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully create queue"
          },
          "422": {
            "description": "unprocessable entity"
          },
          "401": {
            "description": "unauthorized"
          }
        }
      }
    },
    "/members": {
      "post": {
        "summary": "Member Registration",
        "tags": [
          "Accounts"
        ],
        "operationId": "registration",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sign_up",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/sign_up"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfull Registration"
          }
        }
      }
    },
    "/members/login": {
      "post": {
        "summary": "Member Login",
        "tags": [
          "Accounts"
        ],
        "operationId": "login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sign_in",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/login"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfull Login"
          },
          "422": {
            "description": "Successfull Login"
          }
        }
      }
    }
  },
  "definitions": {
    "login": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ],
      "example": {
        "sign_in": {
          "email": "sample@email.com",
          "password": "Abcd#1234"
        }
      }
    },
    "account_change_password": {
      "type": "object",
      "properties": {
        "old_password": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "confirm_password": {
          "type": "string"
        }
      },
      "required": [
        "first_name",
        "last_name",
        "email",
        "mobile"
      ],
      "example": {
        "account": {
          "old_password": "P4ssw0rd#!",
          "password": "w0rdP4ss#!",
          "password_confirmation": "w0rdP4ss#!"
        }
      }
    },
    "account_update": {
      "type": "object",
      "properties": {
        "first_name": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "mobile": {
          "type": "string"
        }
      },
      "example": {
        "account": {
          "first_name": "Samuel",
          "last_name": "Black",
          "mobile": "+33 4 55 44 33"
        }
      }
    },
    "sign_up": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "mobile": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password",
        "name",
        "mobile"
      ],
      "example": {
        "sign_up": {
          "email": "sample@email.com",
          "password": "Abcd#1234",
          "name": "Samuel Black",
          "mobile": "+33 4 55 44 33"
        }
      }
    },
    "queue": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "priority": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "priority"
      ],
      "example": {
        "queue": {
          "name": "Critical Queue",
          "priority": "critical"
        }
      }
    },
    "job": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "priority": {
          "type": "string"
        },
        "job_klass": {
          "type": "string"
        },
        "arguments": {
          "type": "array"
        }
      },
      "required": [
        "name",
        "priority",
        "job_klass"
      ],
      "example": {
        "job": {
          "name": "Queue Job",
          "priority": "high",
          "job_klass": "StoreMoviesJob",
          "arguments": [
            "data_sets/movies.yml"
          ]
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "scheme": "bearer",
      "bearerFormat": "JWT",
      "in": "header",
      "description": "JWT Authorization header using the Bearer scheme. Example: Authorization: Bearer {token}",
      "name": "Authorization"
    }
  }
}